const busRoutes = {
            'route_01': {
                name: 'Tuyến 01',
                color: '#f44336',
                stations: [
                    'cong_truong_me_linh',
                    'ben_bach_dang',
                    'cho_cu', 
                    'cao_thang', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'truong_ernst_thalmann',
                    'cho_nanci',
                    'tran_binh_trong',
                    'nha_van_hoa_quan_5',
                    'hai_thuong_lan_ong',
                    'cho_kim_bien', 
                    'ben_xe_buyt_cho_lon'
                ]
            },
            'route_03': {
                name: 'Tuyến 03',
                color: '#4caf50',
                stations: [
                    'ben_xe_buyt_sai_gon',
                    'truong_emst_thalmann',
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'nam_ky_khoi_nghia', 
                    'cho_cu',
                    'giao_lo_ham_nghi_ton_that_dam', 
                    'ben_bach_dang', 
                    'cong_truong_me_linh', 
                    'nha_hat_thanh_pho', 
                    'benh_vien_nhi_dong_2', 
                    'buu_dien_thanh_pho', 
                    'cong_vien_le_van_tam',
                    'nha_tho_tan_dinh', 
                    'cho_tan_dinh', 
                    'cau_kieu', 
                    'cho_phu_nhuan',
                    'nga_tu_phu_nhuan', 
                    'nga_ba_ho_van_hue', 
                    'chua_van_hanh', 
                    'nga_ba_pham_ngu_lao',
                    'cau_vuot_nga_sau_go_vap', 
                    'nga_tu_phan_van_tri', 
                    'nga_tu_an_nhon',
                    'nga_tu_ga',
                    'cho_thanh_xuan', 
                    'cho_duong',
                    'thanh_xuan'
                ]
            },
            'route_04': {
                name: 'Tuyến 04',
                color: '#ff9800',
                stations: [
                    'ben_xe_buyt_sai_gon', 
                    'truong_emst_thalmann',
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'nam_ky_khoi_nghia', 
                    'cho_cu',
                    'den_tho_an_giao_pasteur', 
                    'nguyen_thi_minh_khai', 
                    'dai_hoc_kien_truc', 
                    'dien_bien_phu',
                    'nha_thieu_nhi_thanh_pho', 
                    'trung_tam_van_hoa_quan_phu_nhuan', 
                    'benh_vien_quan_phu_nhuan', 
                    'vong_xoay_lang_cha_ca',
                    'nga_tu_hoang_hoa_tham', 
                    'nga_ba_binh_gia',
                    'mui_tau_cong_hoa', 
                    'nga_ba_che_lan_vien', 
                    'khu_cong_nghiep_tan_binh',
                    'ben_xe_an_suong'
                ]
            },
            'route_06': {
                name: 'Tuyến 06',
                color: '#9c27b0',
                stations: [
                    'ben_xe_buyt_cho_lon', 
                    'ben_xe_cho_lon', 
                    'benh_vien_cho_ray', 
                    'benh_vien_nguyen_tri_phuong_adv',
                    'cho_an_dong', 
                    'cho_bau_sen', 
                    'dai_hoc_sai_gon', 
                    'dai_hoc_khoa_hoc_tu_nhien',
                    'benh_vien_tu_du', 
                    'nha_van_hoa_lao_dong', 
                    'pasteur',
                    'thao_cam_vien', 
                    'truong_trung_hoc_gia_dinh',
                    'dai_hoc_hutech',
                    'cau_sai_gon',
                    'thao_dien', 
                    'nga_4_tay_hoa', 
                    'lang_thieu_nien_thu_duc', 
                    'nga_ba_chuong_duong', 
                    'truong_dhsp_ky_thuat',
                    'khu_cong_nghe_cao_q9',
                    'dai_hoc_nong_lam', 
                    'ben_xe_buyt_dai_hoc_nong_lam'
                ]
            },
            'route_07': {
                name: 'Tuyến 07',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_cho_lon',
                    'cho_kim_bien',
                    'benh_vien_cho_ray',
                    'dai_hoc_y_duoc',
                    'cong_vien_van_lang',
                    'dai_hoc_kinh_te_q10', 
                    'hoc_vien_quan_y', 
                    'benh_vien_nhi_dong_1', 
                    'nha_hat_hoa_binh', 
                    'vong_xoay_dan_chu', 
                    'ga_sai_gon', 
                    'cho_nguyen_van_troi', 
                    'nga_tu_nguyen_van_troi', 
                    'trung_tam_van_hoa_quan_phu_nhuan', 
                    'benh_vien_quan_phu_nhuan', 
                    'rap_tan_son_nhat', 
                    'cuoi_cong_vien_gia_dinh',
                    'dau_cong_vien_gia_dinh', 
                    'nga_ba_pham_ngu_lao',
                    'bai_hau_can_so_1'
                ]
            },
            'route_08': {
                name: 'Tuyến 08',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_quan_8',
                    'cau_nhi_thien_duong', 
                    'tung_thien_vuong',
                    'cho_xom_cui',
                    'buu_dien_quan_5',
                    'rap_dai_quang',
                    'benh_vien_cho_ray', 
                    'nha_thi_dau_phu_tho', 
                    'benh_vien_trung_vuong',
                    'dai_hoc_bach_khoa', 
                    'buu_dien_phu_tho', 
                    'nga_ba_thanh_thai', 
                    'cho_tan_binh', 
                    'benh_vien_thong_nhat_ltk',
                    'benh_vien_quan_tan_binh', 
                    'cong_vien_hoang_van_thu', 
                    'bao_tang_mien_dong',
                    'nga_tu_phu_nhuan', 
                    'nga_tu_phan_xich_long',
                    'nga_tu_thich_quang_duc',
                    'dai_hoc_van_hien_phu_nhuan',
                    'cong_vien_van_hoa_phu_nhuan', 
                    'lang_ong_ba_chieu', 
                    'cho_ba_chieu', 
                    'cho_hang_xanh', 
                    'nga_ba_hang_xanh', 
                    'nga_tu_binh_trieu', 
                    'chua_uu_dam', 
                    'cau_go_dua', 
                    'nga_tu_to_ngoc_van_pham_van_dong', 
                    'cho_thu_duc', 
                    'nga_ba_chuong_duong', 
                    'truong_dhsp_ky_thuat', 
                    'khu_cong_nghe_cao_q9', 
                    'suoi_tien',
                    'nghia_trang_liet_si_tphcm',
                    'nha_van_hoa_sinh_vien', 
                    'dai_hoc_khoa_hoc_xa_hoi_va_nhan_van',
                    'ben_xe_buyt_dhqg_moi'                  
                ]
            },
            'route_13': {
                name: 'Tuyến 13',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_sai_gon', 
                    'truong_emst_thalmann', 
                    'khach_san_new_world_pht', 
                    'trong_dong', 
                    'vo_van_tan',  
                    'cong_truong_dan_chu',  
                    'nga_ba_chi_hoa', 
                    'chua_buu_da', 
                    'rap_hat_thanh_van', 
                    'cho_hoa_hung', 
                    'cong_vien_le_thi_rieng', 
                    'nga_ba_banh_van_tran', 
                    'ong_ta', 
                    'benh_vien_thong_nhat', 
                    'benh_vien_quan_tan_binh', 
                    'nga_tu_bay_hien', 
                    'nga_ba_hoang_hoa_tham', 
                    'nga_ba_binh_gia',
                    'nga_ba_ap_bac', 
                    'cho_vo_thanh_trang',  
                    'nga_tu_tan_ky_tan_quy',  
                    'mui_tau_cong_hoa',  
                    'nga_ba_che_lan_vien', 
                    'khu_cong_nghiep_tan_binh',  
                    'chua_vinh_phuoc', 
                    'bitis',  
                    'ben_xe_an_suong',  
                    'trung_tam_van_hoa_quan_12',  
                    'nga_ba_cu_cai', 
                    'nga_ba_bui_mon', 
                    'nga_tu_gieng_nuoc',
                    'nga_tu_hoc_mon', 
                    'dan_thang',
                    'nga_ba_lam_son', 
                    'doanh_trai_quan_doi', 
                    'nga_ba_hong_chau', 
                    'cau_an_ha',  
                    'benh_vien_xuyen_a',  
                    'mui_tau_tinh_lo_2',  
                    'nga_tu_quan_doi', 
                    'cau_vuot_cu_chi',
                    'ben_xe_cu_chi'
                ]
            },
            'route_14': {
                name: 'Tuyến 14',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_mien_dong',
                    'nga_nam_liet_si',  
                    'cho_phuong_25', 
                    'dai_hoc_gtvt', 
                    'dai_hoc_ngoai_thuong', 
                    'dai_hoc_hutech', 
                    'nga_ba_nguyen_cuu_van', 
                    'thao_cam_vien', 
                    'dai_truyen_hinh', 
                    'ho_con_rua', 
                    'bao_tang_chung_tich_chien_tranh', 
                    'nguyen_thi_minh_khai',  
                    'benh_vien_tu_du', 
                    'ho_thi_ky',  
                    'cho_phuong_10',  
                    'benh_vien_nhi_dong_1',  
                    'nga_ba_nguyen_kim',  
                    'le_dai_hanh',  
                    'vong_xoay_cay_go', 
                    'cau_ong_buong', 
                    'vong_xoay_phu_lam', 
                    'cong_vien_phu_lam',
                    'vong_xoay_kinh_duong_vuong',
                    'ben_xe_mien_tay'
                ]
            },
            'route_19': {
                name: 'Tuyến 19',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_dhqg_moi',
                    'nha_van_hoa_sinh_vien', 
                    'dai_hoc_an_ninh_nhan_dan',  
                    'khu_du_lich_suoi_tien', 
                    'thao_nguyen', 
                    'dai_hoc_nong_lam', 
                    'cau_vuot_linh_xuan', 
                    'ben_xe_lam_hong', 
                    'cho_tam_hai', 
                    'cho_tam_binh', 
                    'nga_nam_liet_si', 
                    'dai_hoc_gtvt', 
                    'dai_hoc_ngoai_thuong', 
                    'dai_hoc_hutech', 
                    'nga_ba_nguyen_cuu_van',
                    'thao_cam_vien', 
                    'bao_tang_lich_su', 
                    'benh_vien_nhi_dong_2', 
                    'nha_hat_thanh_pho', 
                    'cong_truong_me_linh', 
                    'ben_bach_dang', 
                    'cho_cu',  
                    'tram_trung_chuyen_tren_duong_ham_nghi',
                    'ben_xe_buyt_sai_gon'
                ]
            },
            'route_31': {
                name: 'Tuyến 31',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'dai_hoc_ton_duc_thang', 
                    'dai_hoc_canh_sat', 
                    'cau_da_khoa', 
                    'cau_ly_phuc_man', 
                    'cang_sai_gon',  
                    'cho_xom_chieu', 
                    'cau_ong_lanh', 
                    'nguyen_kim',  
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'nam_ky_khoi_nghia', 
                    'cho_cu', 
                    'pasteur', 
                    'cong_vien_le_van_tam',  
                    'nha_tho_tan_dinh',  
                    'cho_tan_dinh',  
                    'cho_da_kao',  
                    'lang_ong_ba_chieu', 
                    'nha_tho_binh_hoa', 
                    'nga_nam_binh_hoa',  
                    'nha_van_hoa_lao_dong',  
                    'cau_binh_loi_bus31',
                    'cong_vien_dang_thuy_tram'
                ]
            },
            'route_34': {
                name: 'Tuyến 34',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_sai_gon',  
                    'truong_emst_thalmann', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'bao_tang_my_thuat', 
                    'cho_xom_chieu', 
                    'buu_dien_quan_4', 
                    'dai_hoc_nguyen_tat_thanh', 
                    'cang_sai_gon', 
                    'san_bong_da_clb_cang_sg', 
                    'truong_mn_tan_thuan_tay',
                    'cu_xa_ngan_hang', 
                    'nha_tho_thuan_phat', 
                    'mieu_ba_co', 
                    'nga_ba_tan_quy', 
                    'trung_tam_y_te_tan_quy',  
                    'cho_tan_quy', 
                    'cho_chieu', 
                    'cho_tan_my', 
                    'dai_hoc_rmit', 
                    'cau_ong_be',
                    'ben_xe_buyt_quan_8' 
                ]
            },
            'route_36': {
                name: 'Tuyến 36',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_thoi_an', 
                    'ubnd_phuong_thoi_an', 
                    'nha_tho_nu_vuong_hoa_binh', 
                    'cau_cut', 
                    'nha_tho_hop_an', 
                    'nha_tho_ha_noi', 
                    'truong_dai_hoc_hong_bang', 
                    'nga_ba_nguyen_van_luong', 
                    'cho_thong_tay', 
                    'nga_tu_nguyen_oanh', 
                    'bai_hau_can_so_1', 
                    'cho_phan_van_tri', 
                    'nha_tho_binh_hoa', 
                    'benh_vien_gia_dinh', 
                    'lang_ong_ba_chieu', 
                    'cho_tan_dinh', 
                    'dien_bien_phu_q3', 
                    'nha_van_hoa_thanh_nien',
                    'nha_tho_duc_ba', 
                    'pasteur', 
                    'nam_ky_khoi_nghia', 
                    'tram_trung_chuyen_tren_duong_ham_nghi',
                    'ben_xe_buyt_sai_gon'
                ]
            },
            'route_38': {
                name: 'Tuyến 38',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'dau_ben_tan_quy', 
                    'cau_kinh_te', 
                    'chua_anh_linh', 
                    'cao_thang', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'trong_dong', 
                    'cach_mang_thang_8', 
                    'benh_vien_tu_du', 
                    'dai_hoc_khoa_hoc_tu_nhien', 
                    'dai_hoc_su_pham', 
                    'cho_bau_sen', 
                    'benh_vien_30_4', 
                    'nga_tu_nguyen_chi_thanh',
                    'benh_vien_nhi_dong_1', 
                    'nha_tho_dong_tien', 
                    'benh_vien_115', 
                    'dai_hoc_bach_khoa_cong_sau', 
                    'benh_vien_trung_vuong_tht',
                    'nha_thi_dau_phu_tho', 
                    'vong_xoay_le_dai_hanh', 
                    'nga_tu_lac_long_quan',
                    'tram_dang_kiem',
                    'ben_xe_buyt_dam_sen'
                ]
            },
            'route_39': {
                name: 'Tuyến 39',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_sai_gon', 
                    'truong_emst_thalmann', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'bao_tang_my_thuat', 
                    'cho_dan_sinh', 
                    'cho_nga', 
                    'benh_vien_nhiet_doi', 
                    'cho_hoa_binh', 
                    'hai_thuong_lan_ong', 
                    'cho_kim_bien',
                    'cau_lo_gom', 
                    'cau_rach_cay',
                    'chua_sung_quang', 
                    'hang_duong',
                    'ben_xe_mien_tay'

                ]
            },
            'route_44': {
                name: 'Tuyến 44',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_kho_muoi', 
                    'ton_dan',  
                    'truong_chinh_tri_q4', 
                    'le_thi_hong_gam', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'chua_ba_an', 
                    'thu_vien_khoa_hoc_tong_hop', 
                    'so_tai_nguyen_moi_truong',  
                    'bv_nhi_dong_2_ltt', 
                    'ba_son', 
                    'mam_non_hoa_lu',  
                    'cau_vuot_thu_thiem', 
                    'dh_ton_duc_thang',  
                    'truong_trung_hoc_gia_dinh', 
                    'nga_ba_hang_xanh',  
                    'chua_buu_lien',  
                    'chung_cu_thanh_da',  
                    'cho_binh_quoi', 
                    'ben_do_binh_quoi'
                ]
            },
            'route_45': {
                name: 'Tuyến 45',
                color: '#9c27b0',
                stations: [
                    'ben_xe_mien_dong', 
                    'dai_hoc_gtvt', 
                    'dai_hoc_hutech', 
                    'vong_xoay_hang_xanh', 
                    'dai_hoc_hong_bang', 
                    'cau_dien_bien_phu', 
                    'nguyen_van_thu', 
                    'dai_truyen_hinh', 
                    'benh_vien_nhi_dong_2', 
                    'nha_hat_thanh_pho', 
                    'cong_truong_me_linh', 
                    'ben_bach_dang', 
                    'cho_cu', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'truong_ernst_thalmann', 
                    'nguyen_cu_trinh', 
                    'cong_quynh', 
                    'nguyen_trai', 
                    'dai_hoc_su_pham', 
                    'cho_bau_sen', 
                    'benh_vien_30_4', 
                    'nga_tu_ngo_quyen', 
                    'benh_vien_rang_ham_mat', 
                    'benh_vien_cho_ray', 
                    'buu_dien_quan_5', 
                    'tung_thien_vuong', 
                    'chua_phap_quang', 
                    'ben_xe_quan_8', 
                    'binh_hung', 
                    'sau_quoc_lo_50', 
                    'trinh_quang_nghi',        
                    'khu_dan_cu_13a',
                    'dh_kinh_te_nvl'
                ]
            },
            'route_50':{
                name: 'Tuyến 50',
                color: '#9c27b0',
                stations: [
                    'dh_bach_khoa_q10',
                    'dai_hoc_bach_khoa_cong_sau', 
                    'benh_vien_trung_vuong_tht', 
                    'dai_hoc_bach_khoa', 
                    'cho_tan_binh', 
                    'benh_vien_thong_nhat_ltk', 
                    'benh_vien_quan_tan_binh', 
                    'cong_vien_hoang_van_thu', 
                    'rap_tan_son_nhat', 
                    'cuoi_cong_vien_gia_dinh', 
                    'dau_cong_vien_gia_dinh', 
                    'giao_xu_man_coi', 
                    'cau_binh_loi', 
                    'nga_tu_binh_trieu', 
                    'cau_go_da', 
                    'nga_tu_to_ngoc_van_pham_van_dong', 
                    'dai_hoc_csnd', 
                    'tram_cau_vuot_linh_xuan', 
                    'nghia_trang_thanh_pho', 
                    'dai_hoc_nong_lam', 
                    'thu_vien_trung_tam_dhqg', 
                    'dai_hoc_quoc_te_dd_qtst', 
                    'dai_hoc_quoc_te_dd_lqd', 
                    'ktx_khu_a_dhqg', 
                    'ben_xe_buyt_dhqg_moi' 
                ]
            },
            'route_52': {
                name: 'Tuyến 52',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_sai_gon', 
                    'truong_emst_thalmann', 
                    'tram_trung_chuyen_tren_duong_ham_nghi',
                    'cho_cu', 
                    'den_tho_an_giao_pasteur', 
                    'nha_van_hoa_thanh_nien', 
                    'thao_cam_vien', 
                    'truong_trung_hoc_gia_dinh', 
                    'dai_hoc_hutech', 
                    'cau_sai_gon', 
                    'thao_dien', 
                    'nga_4_tay_hoa', 
                    'ga_metro_thu_duc', 
                    'khu_cong_nghe_cao_q9', 
                    'thu_vien_trung_tam_dhqg', 
                    'dai_hoc_quoc_te_dd_qtst', 
                    'dai_hoc_quoc_te_dd_lqd', 
                    'ktx_khu_a_dhqg',
                    'ben_xe_buyt_dhqg_moi'
                ]
            },
            'route_53': {
                name: 'Tuyến 53',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'le_hong_phong', 
                    'benh_vien_truyen_mau_huyet_hoc', 
                    'cho_thai_binh', 
                    'ktx_tran_hung_dao', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'nam_ky_khoi_nghia',  
                    'cho_cu',  
                    'giao_lo_ham_nghi_ton_that_dam', 
                    'ben_bach_dang', 
                    'bao_tang_ton_duc_thang', 
                    'ba_son', 
                    'mam_non_hoa_lu', 
                    'tan_cang', 
                    'thao_dien', 
                    'nga_4_tay_hoa', 
                    'ga_metro_thu_duc', 
                    'dau_duong_le_van_chi', 
                    'nga_ba_le_van_chi', 
                    'dai_hoc_ngan_hang',
                    'ubnd_phuong_linh_trung', 
                    'tram_cau_vuot_linh_xuan', 
                    'nghia_trang_thanh_pho',  
                    'dai_hoc_nong_lam', 
                    'suoi_tien', 
                    'nha_van_hoa_sinh_vien', 
                    'dai_hoc_quoc_te_dd_qtst', 
                    'dai_hoc_quoc_te_dd_lqd', 
                    'ho_da', 
                    'ktx_khu_b_dhqg',
                    'ben_xe_buyt_dhqg'                    
                ]
            },
            'route_55': {
                name: 'Tuyến 55',
                color: '#9c27b0',
                stations: [
                    'ben_cong_vien_phan_mem_quang_trung',
                    'cong_vien_phan_mem_quang_trung', 
                    'dong_bac', 
                    'cong_vien_phan_mem_quang_trung_l', 
                    'cho_cau', 
                    'thpt_nguyen_cong_tru',
                    'ubnd_quan_go_vap', 
                    'nha_tho_xom_thuoc', 
                    'sieu_thi_van_lang', 
                    'benh_vien_175', 
                    'dau_cong_vien_gia_dinh', 
                    'cuoi_cong_vien_gia_dinh',  
                    'dau_dao_duy_anh', 
                    'trung_tam_hoi_nghi_tiec_cuoi_white_palace', 
                    'nga_tu_phu_nhuan', 
                    'nga_tu_phan_xich_long', 
                    'nga_tu_thich_quang_duc', 
                    'dai_hoc_van_hien_phu_nhuan', 
                    'cong_vien_van_hoa_phu_nhuan', 
                    'lang_ong_ba_chieu', 
                    'cho_ba_chieu', 
                    'cho_hang_xanh', 
                    'dai_hoc_hutech', 
                    'cau_sai_gon', 
                    'cong_vien_cau_sai_gon',
                    'ben_xe_van_thanh' 
                ]
            },
            'route_56': {
                name: 'Tuyến 56',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_cho_lon', 
                    'cho_kim_bien',  
                    'benh_vien_cho_ray', 
                    'dai_hoc_y_duoc', 
                    'benh_vien_nguyen_tri_phuong_adv', 
                    'cho_an_dong', 
                    'cho_bau_sen', 
                    'dai_hoc_sai_gon', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'nam_ky_khoi_nghia', 
                    'ben_bach_dang', 
                    'bao_tang_ton_duc_thang', 
                    'ba_son', 
                    'mam_non_hoa_lu',
                    'tan_cang', 
                    'thao_dien', 
                    'nga_4_tay_hoa',
                    'lang_thieu_nien_thu_duc', 
                    'nga_ba_chuong_duong', 
                    'truong_dhsp_ky_thuat',
                    'tram_y_te_phuong_hiep_phu',
                    'ktx_dai_hoc_su_pham_ky_thuat',
                    'nga_3_my_thanh',
                    'nga_ba_lam_vien_1',
                    'nghia_trang_liet_si_tphcm',
                    'ben_xe_mien_dong_moi'              
                ]
            },
            'route_59': {
                name: 'Tuyến 59',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_quan_8', 
                    'cau_nhi_thien_duong', 
                    'ubnd_quan_8', 
                    'pham_hung', 
                    'nha_tho_nam_hai',
                    'benh_vien_nguyen_tri_phuong_ntp',
                    'dai_hoc_kinh_te_q10', 
                    'nha_tho_dong_tien', 
                    'benh_vien_115', 
                    'dai_hoc_bach_khoa_cong_sau',
                    'benh_vien_trung_vuong_tht', 
                    'dai_hoc_bach_khoa', 
                    'cho_tan_binh', 
                    'benh_vien_thong_nhat_ltk',
                    'benh_vien_quan_tan_binh', 
                    'cong_vien_hoang_van_thu', 
                    'rap_tan_son_nhat', 
                    'cuoi_cong_vien_gia_dinh', 
                    'dau_cong_vien_gia_dinh', 
                    'nga_ba_pham_ngu_lao', 
                    'cau_vuot_nga_sau_go_vap', 
                    'nga_tu_phan_van_tri',
                    'nga_tu_an_nhon', 
                    'nga_tu_ga',
                    'ben_xe_nga_tu_ga'
                ]
            },
            
            'route_64': {
                name: 'Tuyến 64',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_quan_8', 
                    'nga_tu_dinh_bo_linh', 
                    'ubnd_phuong_13', 
                    'cau_rach_lang', 
                    'hoc_vien_can_bo', 
                    'nha_van_hoa_lao_dong', 
                    'nga_nam_binh_hoa', 
                    'nha_tho_binh_hoa', 
                    'benh_vien_gia_dinh', 
                    'benh_vien_phuoc_an', 
                    'dai_hoc_van_hien', 
                    'nga_tu_thich_quang_duc', 
                    'nga_tu_phan_xich_long', 
                    'nga_tu_phu_nhuan', 
                    'cong_truoc_svd_quan_khu_7', 
                    'vong_xoay_lang_cha_ca', 
                    'hoi_cho_trien_lam_tan_binh', 
                    'cay_xang_doi', 
                    'nga_tu_bay_hien', 
                    'hoi_chu_thap_do_tan_binh', 
                    'nga_tu_nguyen_hong_dao',
                    'tram_nga_4_thoai_ngoc_hau', 
                    'ubnd_quan_tan_phu', 
                    'thoai_ngoc_hau', 
                    'thuy_ta', 
                    'ben_xe_buyt_dam_sen'
                ]
            },
            'route_65': {
                name: 'Tuyến 65',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                'ben_xe_buyt_sai_gon', 
                'truong_emst_thalmann', 
                'khach_san_new_world_pht',
                'trong_dong', 
                'vo_van_tan', 
                'cong_truong_dan_chu', 
                'nga_ba_chi_hoa', 
                'cho_buu_da', 
                'rap_hat_thanh_van',
                'cho_hoa_hung', 
                'cong_vien_le_thi_rieng',
                'nga_ba_banh_van_tran', 
                'ong_ta', 
                'benh_vien_thong_nhat', 
                'benh_vien_quan_tan_binh', 
                'nga_tu_bay_hien', 
                'nga_ba_hoang_hoa_tham', 
                'nga_ba_binh_gia', 
                'nga_ba_ap_bac', 
                'cho_vo_thanh_trang', 
                'nga_tu_tan_ky_tan_quy', 
                'mui_tau_cong_hoa', 
                'nga_ba_che_lan_vien', 
                'khu_cong_nghiep_tan_binh', 
                'chua_vinh_phuoc', 
                'bitis', 
                'ben_xe_an_suong'

                ]
            },
            'route_69': {
                name: 'Tuyến 69',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_sai_gon', 
                    'truong_emst_thalmann', 
                    'truong_ernst_thalmann', 
                    'nga_sau_phu_dong', 
                    'trong_dong', 
                    'cach_mang_thang_tam', 
                    'ho_thi_ky', 
                    'cho_phuong_10', 
                    'benh_vien_nhi_dong_1', 
                    'nha_tho_dong_tien', 
                    'benh_vien_115', 
                    'dai_hoc_bach_khoa_cong_sau', 
                    'benh_vien_trung_vuong_tht', 
                    'nha_thi_dau_phu_tho', 
                    'cho_chim_xanh', 
                    'ben_xe_buyt_dam_sen', 
                    'dam_sen', 
                    'nga_4_hoa_binh', 
                    'thoai_ngoc_hau', 
                    'ubnd_quan_tan_phu',
                    'tram_pham_van_xao', 
                    'tram_cho_tan_huong', 
                    'tram_nga_4_go_dau_tan_quy', 
                    'tram_tan_ky_tan_quy', 
                    'tram_xang', 
                    'tram_dau_le_trong_tan', 
                    'tram_tay_thanh', 
                    'ubnd_binh_hung_hoa_b', 
                    'truong_tri_tue_viet'

                ]
            },
            'route_75': {
                name: 'Tuyến 75',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_sai_gon', 
                    'truong_emst_thalmann', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'nam_ky_khoi_nghia', 
                    'cho_cu', 
                    'giao_lo_ham_nghi_ton_that_dam', 
                    'cang_sai_gon', 
                    'cau_tan_thuan_2', 
                    'khu_che_xuat_tan_thuan', 
                    'cau_phu_my', 
                    'go_o_moi', 
                    'truong_ngo_quyen_q7', 
                    'pham_huu_lau', 
                    'cho_phu_xuan', 
                    'chua_la', 
                    'pha_binh_khanh', 
                    'cho_binh_khanh', 
                    'nghia_trang_binh_khanh', 
                    'nga_3_an_thoi_dong', 
                    'nga_ba_dao_khi', 
                    'cay_xang_duc_thanh', 
                    'benh_vien_huyen_can_gio', 
                    'ben_xe_buyt_can_gio'
                ]
            },
            
            'route_94': {
                name: 'Tuyến 94',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_buyt_cho_lon', 
                    'ben_xe_cho_lon', 
                    'ta_uyen', 
                    'benh_vien_cho_ray', 
                    'nha_thi_dau_phu_tho', 
                    'benh_vien_trung_vuong', 
                    'dai_hoc_bach_khoa', 
                    'buu_dien_phu_tho', 
                    'nga_ba_thanh_thai', 
                    'cho_tan_binh', 
                    'benh_vien_thong_nhat_ltk', 
                    'benh_vien_quan_tan_binh', 
                    'hoi_cho_trien_lam_tan_binh', 
                    'cay_xang_doi', 
                    'nga_tu_bay_hien', 
                    'nga_ba_hoang_hoa_tham', 
                    'nga_ba_binh_gia', 
                    'nga_ba_ap_bac', 
                    'cho_vo_thanh_trang', 
                    'nga_tu_tan_ky_tan_quy', 
                    'mui_tau_cong_hoa', 
                    'nga_ba_che_lan_vien', 
                    'khu_cong_nghiep_tan_binh', 
                    'chua_vinh_phuoc', 
                    'bitis', 
                    'trung_tam_van_hoa_quan_12' , 
                    'nga_ba_cu_cai', 
                    'nga_ba_bui_mon', 
                    'nga_tu_gieng_nuoc', 
                    'nga_tu_hoc_mon', 
                    'dan_thang', 
                    'nga_ba_lam_son', 
                    'doanh_trai_quan_doi', 
                    'nga_ba_hong_chau' , 
                    'cau_an_ha', 
                    'benh_vien_xuyen_a', 
                    'mui_tau_tinh_lo_2', 
                    'nga_tu_quan_doi', 
                    'cau_vuot_cu_chi' , 
                    'ben_xe_cu_chi'

                ]
            },
            'route_103': {
                name: 'Tuyến 103',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ben_xe_cho_lon_a', 
                    'ben_xe_cho_lon', 
                    'ta_uyen', 
                    'le_dai_hanh', 
                    'nha_thi_dau_phu_tho', 
                    'benh_vien_trung_vuong_ltk',
                    'benh_vien_trung_vuong_tht', 
                    'dai_hoc_bach_khoa_cong_sau', 
                    'truong_thpt_nguyen_du', 
                    'nga_tu_dong_nai', 
                    'cong_vien_le_thi_rieng_q10', 
                    'nga_ba_banh_van_tran', 
                    'ong_ta', 
                    'benh_vien_thong_nhat', 
                    'benh_vien_quan_tan_binh', 
                    'cong_vien_hoang_van_thu', 
                    'parkson_truong_son', 
                    'san_bay_tan_son_nhat', 
                    'ga_quoc_noi_san_bay_tan_son_nhat', 
                    'vong_xoay_nguyen_thai_son',
                    'nga_ba_pham_ngu_lao', 
                    'cau_vuot_nga_sau_go_vap', 
                    'sieu_thi_van_lang', 
                    'nha_tho_xom_thuoc', 
                    'ubnd_quan_go_vap', 
                    'cho_cay_tram', 
                    'nga_ba_le_duc_tho', 
                    'nha_tho_nu_vuong_hoa_binh', 
                    'ubnd_quan_12', 
                    'dd_ben_xe_nga_tu_ga', 
                    'ngoc_lan',
                    'ben_xe_nga_tu_ga'
                ]
            },
            'route_152': {
                name: 'Tuyến 152',
                color: '#9c27b0', //chỉnh màu sau
                stations: [ 
                                'khu_dan_cu_trung_son', 
                    'thao_loan_plaza', 
                    'thao_loan_plaza_259', 
                    'vong_xoay_cau_him_lam', 
                    'truong_duong_ba_trac', 
                    'cho_nanci', 
                    'benh_vien_rang_ham_mat_q1', 
                    'ktx_tran_hung_dao', 
                    'tram_trung_chuyen_tren_duong_ham_nghi', 
                    'nam_ky_khoi_nghia', 
                    'cho_cu', 
                    'den_tho_an_giao_pasteur', 
                    'nguyen_thi_minh_khai', 
                    'dai_hoc_kien_truc', 
                    'dien_bien_phu', 
                    'nha_thieu_nhi_thanh_pho', 
                    'trung_tam_van_hoa_quan_phu_nhuan', 
                    'benh_vien_quan_phu_nhuan', 
                    'cong_truoc_svd_quan_khu_7', 
                    'parkson_truong_son', 
                    'san_bay_tan_son_nhat'
               ]
            },
            'route_155': {
                name: 'Tuyến 155',
                color: '#9c27b0', //chỉnh màu sau
                stations: [
                    'ga_ben_thanh', 
                    'chua_truong_thanh', 
                    'cho_dan_sinh', 
                    'so_giao_dich_chung_khoan', 
                    'den_tho_an_giao_pasteur', 
                    'so_tai_nguyen_moi_truong', 
                    'nha_hat_thanh_pho', 
                    'bv_nhi_dong_2_ltt', 
                    'tram_dung_dinh_doc_lap', 
                    'cho_ben_thanh', 
                    'ga_ben_thanh'

                ]
            },
        };